server:
  port: 8080


spring:
  application:
    name: springcloud-consumer-dept


# Eureka配置, 服务注册到eureka中, 需要一个路径地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-consumer-dept8080
