server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WolfWG/springcloud-config.git #自己远程仓库的地址
# 通过 config-server可以连接到git，访问其中的资源以及配置~